# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Jiang
email: jessicajiang10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Designed by Jessica Jiang.
permalink: /leaf/:title
url: "http://jessicasjiang.github.io" # the base hostname & protocol for your site
twitter_username: jessicasjiang
github_username:  jessicasjiang

# Build settings
markdown: kramdown

# Pagination
gems: [jekyll-paginate]
paginate: 3
paginate_path: /leaf/:num