# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Jiang
email: jessicajiang10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec id feugiat mauris. Maecenas aliquet lectus nec dui ornare, rutrum mollis elit pulvinar. Nunc et aliquet quam. Aliquam consectetur.
permalink: /leaf/:title
url: "http://jessicasjiang.github.io" # the base hostname & protocol for your site
twitter_username: jessicasjiang
github_username:  jessicasjiang

# Build settings
markdown: kramdown